version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./control-panel
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./control-panel:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=development
      - BUN_INSTALL_CACHE=/app/.bun
    depends_on:
      - backend
    init: true
    tty: true
    stdin_open: true